# config/settings.yaml
lidar:
  mock_mode: true
  port: "/dev/ttyUSB0"
  safety_distance: 0.5 # meters
  update_rate: 10 # Hz
  scan_interval: 0.1 # seconds
  communication:
    port: 5555

arduino:
  bus_number: 1  # I2C bus number for hardware mode
  I2C_ADDRESS: 0x08  # I2C address for hardware mode
  mock_mode: true
  mock_settings:
    battery_initial: 12.0  # volts
    battery_drain_rate: 0.0001  # volts/update
    motor_forward_speed: 75  # percentage
    motor_reverse_speed: -75  # percentage
    motor_turn_speed: 50  # percentage

robot:
  max_speed: 0.5 # m/s
  rotation_speed: 0.3 # rad/s
  turn_duration: 1.0 # seconds
  forward_duration: 2  # seconds to move forward
  return_duration: 1  # seconds to turn back
    
camera:
  port: "/dev/video0"
  tolerance: 1 # meters
  close_distance: 1.5 # meters
  focal_length: 577.05
  known_height: 1.60
  colors:
    - [255, 0, 0]    # Red
    - [0, 255, 0]    # Green
    - [0, 0, 255]    # Blue
    - [255, 255, 0]  # Yellow
    - [255, 0, 255]  # Magenta
  origin_point_bias: 320
  model: "yolov8n-pose.onnx"
  max_age: 15
  confidence_threshold: 0.5
  debug_visualization: true
  target_fps: 20  # Target FPS to maintain for consistent performance
  streaming_fps: 30  # Target FPS when in streaming mode (not tracking)
  communication:
    ip: "192.168.1.50"
    tracking_port: 5558
    video_port: 5559
    command_port: 5557

controller:
  communication:
    ip: "192.168.1.50"
    command_port: 5556

visualization:
  communication:
    port: 5556

gps:
  mock_mode: true   # Set to false when real GPS module is connected
  port: "/dev/ttyAMA0"  # The serial port for real GPS (typical for Raspberry Pi)
  baud_rate: 9600  # Default baud rate for NEO-M8N
  update_rate: 1.0  # Update frequency in seconds
  communication:
    port: 5560      # Port for GPS data publication
  
  # Geofence settings
  geofence:
    enabled: true
    # Center point of geofence (default: approximately Central Park, NYC for demo)
    center_lat: 40.785091
    center_lon: -73.968285
    # Radius in meters
    radius: 100
    # Warning distance from fence boundary in meters
    warning_distance: 10
    
  # Mock GPS simulation settings
  mock_settings:
    # Starting position (same as geofence center by default)
    start_lat: 40.785091
    start_lon: -73.968285
    # Max random movement per update (in degrees)
    max_movement: 0.0001
    # Simulate GPS issues occasionally
    simulate_issues: false
    issue_probability: 0.05