# config/settings.yaml
lidar:
  mock_mode: false  # Changed to true since USB devices aren't detected
  port: "/dev/ttyUSB0"
  safety_distance: 1 # meters
  update_rate: 10 # Hz
  scan_interval: 0.1 # seconds
  # Avoidance parameters
  front_detection_angle: 90 # degrees (±45° from center)
  angular_urgency_weight: 0.7 # How much weight to give to angular position (0-1)
  distance_urgency_weight: 0.3 # How much weight to give to distance (0-1)
  # Emergency stop parameters
  emergency_stop_distance: 0.3 # meters - if obstacle closer than this and centered, stop
  emergency_stop_angle: 15 # degrees - center angle for emergency stop detection
  communication:
    port: 5555

arduino:
  bus_number: 1  # I2C bus number for hardware mode
  I2C_ADDRESS: 0x08  # I2C address for hardware mode
  mock_mode: true
  mock_settings:
    battery_initial: 12.0  # volts
    battery_drain_rate: 0.0001  # volts/update
    motor_forward_speed: 75  # percentage
    motor_reverse_speed: -75  # percentage
    motor_turn_speed: 50  # percentage

robot:
  max_speed: 0.5 # m/s
  rotation_speed: 0.3 # rad/s
  turn_duration: 1.0 # seconds
  forward_duration: 2  # seconds to move forward
  return_duration: 1  # seconds to turn back
  avoidance_timeout: 5.0  # seconds before forcing a return to tracking
    
camera:
  port: "/dev/video0"
  tolerance: 1 # meters
  close_distance: 0.1 # meters
  focal_length: 577.05
  known_height: 1.60
  colors:
    - [255, 0, 0]    # Red
    - [0, 255, 0]    # Green
    - [0, 0, 255]    # Blue
    - [255, 255, 0]  # Yellow
    - [255, 0, 255]  # Magenta
  origin_point_bias: 320
  model: "yolov8n-pose.onnx"
  max_age: 15
  confidence_threshold: 0.5
  debug_visualization: true
  target_fps: 20  # Target FPS to maintain for consistent performance
  streaming_fps: 30  # Target FPS when in streaming mode (not tracking)
  communication:
    ip: "192.168.1.50"
    tracking_port: 5558
    video_port: 5559
    command_port: 5557

controller:
  communication:
    ip: "192.168.1.40"
    command_port: 5556

visualization:
  communication:
    port: 5556

gps:
  mock_mode: false   # Set to false when real GPS module is connected
  port: "/dev/ttyAMA0"  # The serial port for real GPS (typical for Raspberry Pi)
  baud_rate: 38400  # Default baud rate for NEO-M8N
  update_rate: 1.0  # Update frequency in seconds
  communication:
    port: 5560      # Port for GPS data publication
  
  # Geofence settings
  geofence:
    enabled: true
    # Path to the geofence JSON file (polygon coordinates)
    geofence_file: "config/geofence.json"
    # Warning distance from fence boundary in meters
    warning_distance: 10
    
  # Mock GPS simulation settings
  mock_settings:
    # Starting position (same as geofence center by default)
    start_lat: 40.785091
    start_lon: -73.968285
    # Max random movement per update (in degrees)
    max_movement: 0.0001
    # Simulate GPS issues occasionally
    simulate_issues: false
    issue_probability: 0.05
