# config/settings.yaml
lidar:
  port: "/dev/ttyUSB0"
  safety_distance: 1.5 # meters
  update_rate: 10 # Hz

arduino:
  port: "/dev/ttyACM0"
  baudrate: 115200

robot:
  max_speed: 0.5 # m/s
  rotation_speed: 0.3 # rad/s
